DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS deviations;
DROP TABLE IF EXISTS baseline_fingerprints;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS runs;
DROP TABLE IF EXISTS releases;
DROP TABLE IF EXISTS packages;
